Alura.LeilaoOnline.WebApp/Models/RegistroViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Alura.LeilaoOnline.WebApp.Models
{
    public class RegistroViewModel
    {
        [Required]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Endereço de Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Confirmação de Senha")]
        [DataType(DataType.Password)]
        [Compare(nameof(Password))]
        public string ConfirmPassword { get; set; }

    }
}

Alura.LeilaoOnline.WebApp/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Dados;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Extensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    public class AutenticacaoController : Controller
    {
        private readonly IRepositorio<Usuario> _repo;

        public AutenticacaoController(IRepositorio<Usuario> repositorio)
        {
            _repo = repositorio;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = _repo.Todos.First(u => u.Email == model.Login && u.Senha == model.Password);
                if (usuario != null)
                {
                    usuario = _repo.BuscarPorId(usuario.Id);
                    //autenticar
                    HttpContext.Session.Set<Usuario>("usuarioLogado", usuario);
                    if (usuario.Interessada == null)
                    {
                        return RedirectToAction("Index", "Leiloes");
                    }
                    return RedirectToAction("Index", "Interessadas");
                }
                ModelState.AddModelError("usuarioInvalido", "Usuário não encontrado");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("usuarioLogado");
            return RedirectToAction("Index", new { Controller = "Home" });
        }
    }
}

Alura.LeilaoOnline.WebApp/Controllers/LeiloesController.cs
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Dados;
using System.Collections.Generic;
using System.Linq;
using Alura.LeilaoOnline.WebApp.Extensions;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Alura.LeilaoOnline.WebApp.Filtros;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [AutorizacaoFilterAttribute]
    public class LeiloesController : Controller
    {
        private readonly IRepositorio<Leilao> _repo;
        private readonly IHostingEnvironment _env;

        private string TentaGravarImagemDestaqueERetornaSeuNome(IFormFile upload)
        {
            if (upload != null)
            {
                var nomeArquivoServidor = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    upload.FileName);
                using (var stream = new FileStream(nomeArquivoServidor, FileMode.OpenOrCreate))
                {
                    upload.CopyTo(stream);
                }
            }
            return $"/images/{upload.FileName}";
        }

        public LeiloesController(IRepositorio<Leilao> repositorio, IHostingEnvironment environment)
        {
            _repo = repositorio;
            _env = environment;
        }

        public IActionResult Index(Paginacao paginacao)
        {
            var leiloes = _repo.Todos
                .Select(l => l.ToViewModel())
                .ToListaPaginada(paginacao);
            return View(leiloes);
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(LeilaoViewModel model)
        {
            if (ModelState.IsValid)
            {
                //gravar arquivo com a imagem definida
                model.Imagem = this.TentaGravarImagemDestaqueERetornaSeuNome(model.ArquivoImagem);
                var novoLeilao = model.ToModel();
                _repo.Incluir(novoLeilao);
                return RedirectToAction("Index");
            }
            return View("Novo", model);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            //var leilao = _repo.BuscarPorId(id);
            var leilao = new LeilaoViewModel();
            if(leilao != null)
            {
                //_repo.Excluir(leilao);
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        //[HttpGet]
        //public IActionResult Visualiza(int id)
        //{
        //    var leilao = _repo.BuscarPorId(id);
        //    if(leilao != null) {
        //      return View(leilao);
        //    }
        //    return NotFound();
        //}
    }
}

Alura.LeilaoOnline.WebApp/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Dados;
using Alura.LeilaoOnline.Core;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IRepositorio<Usuario> _repo;

        public UsuariosController(IRepositorio<Usuario> repositorio)
        {
            _repo = repositorio;
        }

        [HttpPost]
        public IActionResult Registro(RegistroViewModel model)
        {
            if (ModelState.IsValid)
            {
                //registrar usuário/interessado
                var usuario = new Usuario { Email = model.Email, Senha = model.Password, Interessada = new Interessada(model.Nome) };
                _repo.Incluir(usuario);
                return RedirectToAction("Agradecimento");
            }
            return BadRequest();
        }

        [HttpGet]
        public IActionResult Agradecimento()
        {
            return View();
        }
    }
}

Alura.LeilaoOnline.WebApp/Views/Shared/_Cabecalho.cshtml
@{ 
    var usuarioLogado = Context.Session.Get<Usuario>("usuarioLogado");
}

<div class="navbar-fixed">
    <nav class="white z-depth-2" role="navigation">
        <div class="nav-wrapper">
            <div class="container">
                <a id="logo-container" asp-controller="Home" asp-action="Index" class="brand-logo">
                    <span>Leilões</span>
                    <span>online</span>
                </a>

                <!-- Dropdown Structure -->
                <ul id="dropdown1" class="dropdown-content">
                    <li><a href="#!">Meu Perfil</a></li>
                    <li class="divider"></li>
                    <li><a id="logout" asp-controller="Autenticacao" asp-action="Logout">Logout</a></li>
                </ul>
                <ul class="right hide-on-med-and-down">
                    @if (usuarioLogado == null)
                    {
                        <li><a asp-controller="Autenticacao" asp-action="Login">Login</a></li>
                    }
                    else
                    {
                        if (usuarioLogado.Interessada == null)
                        {
                            <li><a asp-controller="Leiloes" asp-action="Index">Leilões</a></li>
                        }
                        else
                        {
                            <li><a asp-controller="Interessadas" asp-action="Index">Dashboard</a></li>
                        }
                        <li class="center-align">
                            <a id="meu-perfil" class="dropdown-trigger" href="#" data-target="dropdown1">
                                <i class="material-icons large">account_circle</i>
                                <i class="material-icons">arrow_drop_down</i>
                            </a>
                        </li>
                    }
                </ul>

                <ul id="nav-mobile" class="sidenav">
                    <li><a asp-controller="Leiloes" asp-action="Index">Leilões</a></li>
                    <li><a href="#">Usuários</a></li>
                    <li><a href="#">Perfil</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </div>
    </nav>
</div>

Alura.LeilaoOnline.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"]</title>
    <!-- CSS  -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
</head>
<body class="grey lighten-4">
    <partial name="_Cabecalho" />
    @RenderBody()
    <partial name="_Rodape" />

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/materialize.js"></script>
    <script src="~/js/app.js"></script>
    <script src="~/js/init.js"></script>
    @RenderSection("Scripts", false);
</body>
</html>

Alura.LeilaoOnline.WebApp/Views/Shared/_ModalLance.cshtml
@model LanceViewModel
<form id="formDarLance" asp-controller="Interessadas" asp-action="OfertaLance">
    <input type="hidden" asp-for="LeilaoId" />
    <input type="hidden" asp-for="UsuarioLogadoId" />
    <input class="browser-default input-lance" asp-for="Valor" min="0"/>
    <button id="btnDarLance" class="btn waves-effect waves-light yellow darken-4 btn-flat white-text">
        Dar Lance
    </button>
</form>

Alura.LeilaoOnline.WebApp/Views/Shared/_Registro.cshtml
@model Alura.LeilaoOnline.WebApp.Models.RegistroViewModel

<form class="card-panel" asp-action="Registro" asp-controller="Usuarios">
    <div class="input-field">
        <input asp-for="Nome" />
        <label asp-for="Nome"></label>
        <span class="helper-text msg-erro" asp-validation-for="Nome"></span>
    </div>
    <div class="input-field">
        <input asp-for="Email" />
        <label asp-for="Email"></label>
        <span class="helper-text msg-erro" asp-validation-for="Email"></span>
    </div>
    <div class="input-field">
        <input asp-for="Password" />
        <label asp-for="Password"></label>
        <span class="helper-text msg-erro" asp-validation-for="Password"></span>
    </div>
    <div class="input-field">
        <input asp-for="ConfirmPassword" />
        <label asp-for="ConfirmPassword"></label>
        <span class="helper-text msg-erro" asp-validation-for="ConfirmPassword"></span>
    </div>
    <button id="btnRegistro" class="btn waves-effect waves-light brown darken-3 z-depth-0">Registrar</button>
</form>

Alura.LeilaoOnline.WebApp/Views/Shared/_Rodape.cshtml
<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Sobre o sistema</h5>
                <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros.</p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Pré-Requisitos</h5>
                <ul>
                    <li><a class="white-text" href="#!">AspNet Core MVC</a></li>
                    <li><a class="white-text" href="#!">Entity Framework Core</a></li>
                    <li><a class="white-text" href="#!">Identity</a></li>
                    <li><a class="white-text" href="#!">Testes com xUnit</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Referências</h5>
                <ul>
                    <li><a class="white-text" href="#!">Projeto no Github</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="brown-text text-lighten-3" href="http://github.com/dpcosta">Daniel Portugal</a>
        </div>
    </div>
</footer>