Alura.LeilaoOnline.WebApp/Models/PesquisaLeiloesViewModel.cs
namespace Alura.LeilaoOnline.WebApp.Models
{
    public class PesquisaLeiloesViewModel
    {
        public string Termo { get; set; }
        public string[] Categorias { get; set; }
        public string Andamento { get; set; }
    }
}

Alura.LeilaoOnline.WebApp/Controllers/InteressadasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.WebApp.Filtros;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Dados;
using Alura.LeilaoOnline.WebApp.Extensions;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [AutorizacaoFilter]
    public class InteressadasController : Controller
    {

        private readonly IRepositorio<Leilao> _repoLeilao;
        private readonly IRepositorio<Interessada> _repoInteressada;

        public InteressadasController(
            IRepositorio<Leilao> repoLeilao, 
            IRepositorio<Interessada> repoInteressada)
        {
            _repoLeilao = repoLeilao;
            _repoInteressada = repoInteressada;
        }

        private IEnumerable<Leilao> PesquisaLeiloes(PesquisaLeiloesViewModel pesquisa)
        {
            if (pesquisa.Andamento == null && pesquisa.Categorias == null && pesquisa.Termo == null)
                return null;
            var leiloes = _repoLeilao.Todos;
            if (!string.IsNullOrEmpty(pesquisa.Andamento))
            {
                leiloes = leiloes.Where(l => l.Estado == EstadoLeilao.LeilaoEmAndamento);
            }
            if (!string.IsNullOrWhiteSpace(pesquisa.Termo))
            {
                leiloes = leiloes.Where(l => l.Titulo.Contains(pesquisa.Termo, StringComparison.InvariantCultureIgnoreCase));
            }
            if (pesquisa.Categorias != null && pesquisa.Categorias.Length > 0)
            {
                leiloes = leiloes.Where(l => pesquisa.Categorias.Contains(l.Categoria));
            }
            return leiloes.ToList();
        }

        public IActionResult Index(PesquisaLeiloesViewModel pesquisa)
        {
            var usuarioLogado = this.HttpContext.Session.Get<Usuario>("usuarioLogado");
            var interessada = _repoInteressada
                .BuscarPorId(usuarioLogado.Interessada.Id);
            var model = new DashboardInteressadaViewModel
            {
                MinhasOfertas = interessada.Lances,
                LeiloesFavoritos = interessada.Favoritos.Select(f => f.LeilaoFavorito),
                LeiloesPesquisados = PesquisaLeiloes(pesquisa)
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult OfertaLance(LanceViewModel model)
        {
            if (ModelState.IsValid)
            {
                Leilao leilao = _repoLeilao.BuscarPorId(model.LeilaoId);
                Interessada interessada = _repoInteressada.BuscarPorId(model.UsuarioLogadoId);
                leilao.RecebeLance(interessada, model.Valor);
                _repoLeilao.Alterar(leilao); //?
                return Ok();
            }
            return BadRequest();
        }

        [HttpPost]
        public IActionResult SeguirLeilao(FavoritoViewModel model)
        {
            var leilao = _repoLeilao.BuscarPorId(model.IdLeilao);
            if (leilao != null)
            {
                var favorito = new Favorito
                {
                    IdLeilao = model.IdLeilao,
                    IdInteressada = model.IdInteressada
                };
                leilao.Seguidores.Add(favorito);
                _repoLeilao.Alterar(leilao);
                return Ok();
            }
            return NotFound();
        }

        [HttpPost]
        public IActionResult AbandonarLeilao(FavoritoViewModel model)
        {
            var leilao = _repoLeilao.BuscarPorId(model.IdLeilao);
            if (leilao != null)
            {
                var favorito = leilao.Seguidores
                    .FirstOrDefault(s =>
                        s.IdLeilao == model.IdLeilao &&
                        s.IdInteressada == model.IdInteressada);
                leilao.Seguidores.Remove(favorito);
                _repoLeilao.Alterar(leilao);
                return Ok();
            }
            return NotFound();
        }
    }
}

Alura.LeilaoOnline.WebApp/Views/Interessadas/Index.cshtml
@model DashboardInteressadaViewModel
@{
    ViewData["Title"] = "Dashboard";
}
<div class="container">
    <div class="row">
        @if (Model.LeiloesPesquisados != null && Model.LeiloesPesquisados.Count() > 0)
        {
            <div class="col s12">
                <div class="card leiloes-pesquisados">
                    <div class="card-content">
                        <span class="card-title">Resultado da pesquisa</span>
                        <table class="striped">
                            <thead>
                                <tr>
                                    <th>Título</th>
                                    <th>Categoria</th>
                                    <th>Situação</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var leilao in Model.LeiloesPesquisados)
                                {
                                    <tr>
                                        <td>
                                            <a asp-controller="Home" asp-action="Detalhes" asp-route-id="@leilao.Id">@leilao.Titulo</a>
                                        </td>
                                        <td>@leilao.Categoria</td>
                                        <td>@leilao.Estado.ParaTexto()</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        <div class="col s12 m8">
            <div class="card minhas-ofertas">
                <div class="card-content">
                    <span class="card-title">Minhas Ofertas</span>
                    <table class="striped">
                        <thead>
                            <tr>
                                <th>Leilão</th>
                                <th>Valor</th>
                                <th>Situação</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var lance in Model.MinhasOfertas)
                            {
                                <tr>
                                    <td>@lance.Leilao.Titulo</td>
                                    <td>@lance.Valor</td>
                                    <td>Atual</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Leilões Favoritos</span>
                    <ul class="collection">
                        @foreach (var favorito in Model.LeiloesFavoritos)
                        {
                            <li class="collection-item">
                                @favorito.Titulo
                                <a href="#!" class="secondary-content">
                                    <i class="material-icons">close</i>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Pesquisar Leilões</span>
                    <partial name="PesquisaLeiloes" model="new PesquisaLeiloesViewModel()" />
                </div>
            </div>
            <!--div.card-->
        </div>
    </div>
</div>

Alura.LeilaoOnline.WebApp/Views/Interessadas/PesquisaLeiloes.cshtml
@model PesquisaLeiloesViewModel
<form asp-controller="Interessadas" asp-action="Index">
    <div class="input-field">
        <select multiple name="categorias">
            <option value="Automóveis" selected>Automóveis</option>
            <option value="Arte e Pintura" selected>Arte</option>
            <option value="Item de Colecionador" selected>Coleções</option>
        </select>
        <label>Por categoria</label>
    </div>
    <div class="input-field">
        <input id="termo" type="text" name="termo" value="" />
        <label for="termo">Por título</label>
    </div>
    <div class="input-field">
        <div class="switch">
            <label>
                Todos
                <input type="checkbox" name="andamento">
                <span class="lever"></span>
                Apenas em andamento
            </label>
        </div>
    </div>
    <button class="btn waves-effect waves-light">Pesquisar</button>
</form>