Alura.LeilaoOnline.WebApp/Controllers/LeiloesController.cs
using Microsoft.AspNetCore.Mvc;
using Alura.LeilaoOnline.Core;
using Alura.LeilaoOnline.WebApp.Models;
using Alura.LeilaoOnline.WebApp.Dados;
using System.Collections.Generic;
using System.Linq;
using Alura.LeilaoOnline.WebApp.Extensions;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Alura.LeilaoOnline.WebApp.Filtros;

namespace Alura.LeilaoOnline.WebApp.Controllers
{
    [AutorizacaoFilterAttribute]
    public class LeiloesController : Controller
    {
        private readonly IRepositorio<Leilao> _repo;
        private readonly IHostingEnvironment _env;

        private string TentaGravarImagemDestaqueERetornaSeuNome(IFormFile upload)
        {
            if (upload != null)
            {
                var nomeArquivoServidor = Path.Combine(
                    _env.WebRootPath,
                    "images",
                    upload.FileName);
                using (var stream = new FileStream(nomeArquivoServidor, FileMode.OpenOrCreate))
                {
                    upload.CopyTo(stream);
                }
            }
            return $"/images/{upload.FileName}";
        }

        public LeiloesController(IRepositorio<Leilao> repositorio, IHostingEnvironment environment)
        {
            _repo = repositorio;
            _env = environment;
        }

        public IActionResult Index(Paginacao paginacao)
        {
            var leiloes = _repo.Todos
                .Select(l => l.ToViewModel())
                .ToListaPaginada(paginacao);
            return View(leiloes);
        }

        [HttpGet]
        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Novo(LeilaoViewModel model)
        {
            if (ModelState.IsValid)
            {
                //gravar arquivo com a imagem definida
                model.Imagem = this.TentaGravarImagemDestaqueERetornaSeuNome(model.ArquivoImagem);
                var novoLeilao = model.ToModel();
                _repo.Incluir(novoLeilao);
                return RedirectToAction("Index");
            }
            return View("Novo", model);
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            //var leilao = _repo.BuscarPorId(id);
            var leilao = new LeilaoViewModel();
            if(leilao != null)
            {
                //_repo.Excluir(leilao);
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        //[HttpGet]
        //public IActionResult Visualiza(int id)
        //{
        //    var leilao = _repo.BuscarPorId(id);
        //    if(leilao != null) {
        //      return View(leilao);
        //    }
        //    return NotFound();
        //}
    }
}

Alura.LeilaoOnline.WebApp/Views/Leiloes/Categoria.cshtml
@{
    ViewData["Title"] = "Categoria";
}

<div class="container">
    <div class="section">
        <div class="row">
            <div class="col s12">
                <h4>Leilões da categoria @ViewData["categoria"]</h4>
            </div>
            <div class="col s12 m3">
                <div class="card">
                    <div class="card-image">
                        <img src="~/images/painting1.jpg" width="300px">
                        <span class="card-title">Réplica de Pintura</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quae odio amet nisi facere tempore.
                        </p>
                    </div>
                    <div class="card-action center">
                        <a asp-controller="Home" asp-action="Detalhes">Detalhes</a>
                    </div>
                </div>
            </div>
            <div class="col s12 m3">
                <div class="card">
                    <div class="card-image">
                        <img src="~/images/carro1.jpg" width="300px">
                        <span class="card-title">Buick Antigo</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quae odio amet nisi facere tempore.
                        </p>
                    </div>
                    <div class="card-action center">
                        <a href="#">Detalhes</a>
                    </div>
                </div>
            </div>
            <div class="col s12 m3">
                <div class="card">
                    <div class="card-image">
                        <img src="~/images/instrumento1.jpg" width="300px">
                        <span class="card-title">Guitarra Special</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quae odio amet nisi facere tempore.
                        </p>
                    </div>
                    <div class="card-action center">
                        <a href="#">Detalhes</a>
                    </div>
                </div>
            </div>
            <div class="col s12 m3">
                <div class="card">
                    <div class="card-image">
                        <img src="~/images/instrumento2.jpg" width="300px">
                        <span class="card-title">Piano Clássico</span>
                    </div>
                    <div class="card-content">
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quae odio amet nisi facere tempore.
                        </p>
                    </div>
                    <div class="card-action center">
                        <a href="#">Fazer Oferta</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Alura.LeilaoOnline.WebApp/Views/Leiloes/Index.cshtml
@model Pagina<LeilaoViewModel>

@{
    ViewData["Title"] = "Index";
}

@*<div class="fixed-action-btn">
    <a asp-controller="Leiloes" asp-action="Novo" class="btn-floating btn-large waves-effect waves-light">
        <i class="material-icons">add</i>
    </a>
</div>*@

<!-- Modal Structure -->
<div id="modalConfirmaDelLeilao" class="modal">
    <div class="modal-content">
        <h4>Confirmação</h4>
        <p>Tem certeza que deseja excluir o leilão?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="modal-close btn-flat">Não</a>
        <form asp-action="Remove" asp-controller="Leiloes">
            <input type="hidden" name="id" value="2" class="inline" />
            <button class="modal-close waves-effect waves-green btn-flat">Sim</button>
        </form>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col s12">
            <!-- Tabela com os leilões cadastrados -->
            <div class="card">
                <div class="card-content">
                    <h4 class="card-title">
                        Leilões cadastrados no sistema
                        <a asp-action="Novo" asp-controller="Leiloes" class="right red btn-small btn-floating waves-effect waves-light">
                            <i class="material-icons">add</i>
                        </a>

                    </h4>
                    <table class="striped responsive-table">
                        <thead>
                            <tr>
                                <th>Descrição</th>
                                <th>Valor Inicial</th>
                                <th>Categoria</th>
                                <th>Estado Atual</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var leilao in Model.Items)
                            {
                                <tr>
                                    <td>@leilao.Titulo</td>
                                    <td>@leilao.ValorInicial</td>
                                    <td>@leilao.Categoria</td>
                                    <td>@leilao.Estado.ParaTexto()</td>
                                    <td>
                                        <a class="modal-trigger black-text" href="#modalConfirmaDelLeilao"><i class="material-icons">close</i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!--card.content>table-->
                <div class="card-action">
                    <ul class="pagination right-align">
                        @{
                            var anteriorDisabled = (Model.Info.Anterior <= 0) ? "disabled" : "";
                            //var proximaDisabled = (Model.Info.Proxima > )
                        }
                        <li class="@anteriorDisabled">
                            <a asp-action="Index" asp-route-pagina="@Model.Info.Anterior" class="grey-text text-lighten-2">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                        <li class="active waves-effect red">
                            <a href="#!" class="white-text">@Model.Info.Atual</a>
                        </li>
                        <li class="waves-effect">
                            <a asp-action="Index" asp-route-pagina="@Model.Info.Proxima" class="grey-text">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    </ul>
                    <!--ul.pagination-->
                </div>
            </div>
            <!--div.card-->
        </div>
        
    </div>
</div>

Alura.LeilaoOnline.WebApp/Views/Leiloes/Novo.cshtml
@model LeilaoViewModel
@{
    ViewData["Title"] = "Novo Leilão";
}

<form class="container" asp-action="Novo" asp-controller="Leiloes" enctype="multipart/form-data">
    <h4>Inclusão de Leilão</h4>
    <div class="row">
        <div class="col s12 m8">
            <div class="card">
                <div class="card-content">
                    <h5 class="card-title">Informações básicas</h5>
                    <div class="input-field">
                        <input asp-for="Titulo" class="validate" />
                        <label asp-for="Titulo"></label>
                        <span class="helper-text msg-erro" asp-validation-for="Titulo"></span>
                    </div>
                    <!--div.input-field titulo-->
                    <div class="input-field">
                        <textarea asp-for="Descricao" class="validate materialize-textarea"></textarea>
                        <label asp-for="Descricao"></label>
                        <span class="helper-text msg-erro" asp-validation-for="Descricao"></span>
                    </div>
                    <!--div.input-field descricao-->
                    <div class="row">
                        <div class="input-field col s6">
                            <select asp-for="Categoria" class="browser-default">
                                <option value="" selected disabled>Escolha a categoria</option>
                                <option value="Automóveis">Automóveis</option>
                                <option value="Item de Colecionador">Item de Colecionador</option>
                                <option value="Arte e Pintura">Arte e Pintura</option>
                            </select>
                            <span class="helper-text msg-erro" asp-validation-for="Categoria"></span>
                        </div>
                        <!--div.input-field categoria-->
                        <div class="input-field col s6">
                            <input asp-for="ValorInicial" class="validate">
                            <label asp-for="ValorInicial"></label>
                            <span class="helper-text msg-erro" asp-validation-for="ValorInicial"></span>
                        </div>
                        <!--div.input-field valorInicial-->
                    </div>
                    <!--div.row-->
                </div>
                <!--div.card-content-->
                <div class="card-action">
                    <button type="submit" class="btn waves-effect waves-light z-depth-0"><i class="material-icons left">archive</i>Salvar</button>
                </div>
            </div>
            <!--div.card-->
        </div>
        <!--div.col1 infoBasica-->
        <div class="col s12 m4">
            <div class="card imagem">
                <div class="card-image file-field">
                    <img id="imgPoster" class="responsive-img" src="~/images/poster-vazio.png" />
                    <a class="btn-floating halfway-fab waves-effect waves-light">
                        <i class="material-icons">mode_edit</i>
                        <input asp-for="ArquivoImagem">
                    </a>
                </div>
                <!--div.card-image-->
                <div class="card-content">
                    <span class="msg-erro" asp-validation-for="ArquivoImagem">Nenhuma imagem definida.</span>
                </div>
                <!--div.card-content-->
            </div>
            <!--div.card-->
        </div>
        <!--div.col2 imagem-->
        <div class="col s12 m4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Pregão</span>
                    <div class="row">
                        <div class="input-field col s6">
                            <input type="text" asp-for="InicioPregao" class="validate datepicker">
                            <label asp-for="InicioPregao"></label>
                            <span class="helper-text msg-erro" asp-validation-for="InicioPregao"></span>
                        </div>
                        <div class="input-field col s6">
                            <input type="text" asp-for="TerminoPregao" class="validate datepicker">
                            <label asp-for="TerminoPregao"></label>
                            <span class="helper-text msg-erro" asp-validation-for="TerminoPregao"></span>
                        </div>
                    </div>
                </div>
                <!--div.card-content-->
            </div>
            <!--div.card-->
        </div>
        <!--div.col3 infoPregao-->
    </div>
    <!--div.row-->
        
</form>